### ISSUE TITLE
Error installing requirements

### ISSUE THREAD

**Issue by henrikstroem** [arocks/edge#17]
```
$ pip install -r requirements.txt 
Traceback (most recent call last):
  File "/Users/henrik/Sandbox/edge2/p34env/lib/python3.4/site-packages/pip/_vendor/__init__.py", line 61, in load_module
    __import__(name)
ImportError: No module named 'pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname.CertificateError'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/henrik/Sandbox/edge2/p34env/lib/python3.4/site-packages/pip/_vendor/__init__.py", line 78, in load_module
    __import__(real_name)
ImportError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/henrik/Sandbox/edge2/p34env/bin/pip", line 7, in <module>
    from pip import main
  File "/Users/henrik/Sandbox/edge2/p34env/lib/python3.4/site-packages/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/Users/henrik/Sandbox/edge2/p34env/lib/python3.4/site-packages/pip/vcs/mercurial.py", line 11, in <module>
    from pip.download import path_to_url
  File "/Users/henrik/Sandbox/edge2/p34env/lib/python3.4/site-packages/pip/download.py", line 30, in <module>
    from pip._vendor import requests, six
  File "/Users/henrik/Sandbox/edge2/p34env/lib/python3.4/site-packages/pip/_vendor/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/Users/henrik/Sandbox/edge2/p34env/lib/python3.4/site-packages/pip/_vendor/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/Users/henrik/Sandbox/edge2/p34env/lib/python3.4/site-packages/pip/_vendor/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/Users/henrik/Sandbox/edge2/p34env/lib/python3.4/site-packages/pip/_vendor/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/Users/henrik/Sandbox/edge2/p34env/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/Users/henrik/Sandbox/edge2/p34env/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 29, in <module>
    from .packages.ssl_match_hostname import CertificateError
  File "/Users/henrik/Sandbox/edge2/p34env/lib/python3.4/site-packages/pip/_vendor/__init__.py", line 81, in load_module
    raise ImportError("No module named '%s'" % (name,))
ImportError: No module named 'pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname.CertificateError'
```

**Comment by arocks** [comment]
This looks like a pip issue. Have you tried upgrading pip like `pip install --upgrade pip`? Or you could install the packages listed in `requirements/base.txt` one by one and find out the offending package.
