### ISSUE TITLE
Startproject zipfile.BadZipfile: File is not a zip file

### ISSUE THREAD

**Issue by rayzl0523minibear** [arocks/edge#19]
Hi
When I use the command `django-admin.py startproject --template=https://github.com/arocks/edge/archive/master.zip --extension=py,md,html,env example` to start a new project which name is example under Python2.7.6, encounter a error: zipfile.BadZipfile: File is not a zip file.

Following is all my verbose error information:
django-admin.py startproject --template=https://github.com/arocks/edge/archive/master.zip --extension=py,md,html,env example
Traceback (most recent call last):
  File "/usr/local/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Library/Python/2.7/site-packages/django/core/management/commands/startproject.py", line 31, in handle
    super(Command, self).handle('project', project_name, target, **options)
  File "/Library/Python/2.7/site-packages/django/core/management/templates.py", line 122, in handle
    base_subdir)
  File "/Library/Python/2.7/site-packages/django/core/management/templates.py", line 205, in handle_template
    return self.extract(absolute_path)
  File "/Library/Python/2.7/site-packages/django/core/management/templates.py", line 299, in extract
    archive.extract(filename, tempdir)
  File "/Library/Python/2.7/site-packages/django/utils/archive.py", line 49, in extract
    with Archive(path) as archive:
  File "/Library/Python/2.7/site-packages/django/utils/archive.py", line 58, in __init__
    self._archive = self._archive_cls(file)(file)
  File "/Library/Python/2.7/site-packages/django/utils/archive.py", line 181, in __init__
    self._archive = zipfile.ZipFile(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 766, in __init__
    self._RealGetContents()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file

I have installed a django with version 1.7.6 in an virtualenv.

**Comment by arocks** [comment]
Hi @rayzl0523minibear ,

There could be several reasons for the file getting corrupted such as being behind a proxy. If that's the case then could you try downloading the zip file from your browser? Download [edge-master.zip](https://github.com/arocks/edge/archive/master.zip) (right-click and save the link) and run this command wherever you saved the file:

    django-admin.py startproject --template=edge-master.zip --extension=py,md,html,env example    

If it worked, then you can delete the zip file.

**Comment by rayzl0523minibear** [comment]
Yeah, it works. But I don't have any idea about the error when using a .zip template. Anyway, I can use the edge is OK. Thank you.
