### ISSUE TITLE
utils is not a package

### ISSUE THREAD

**Issue by musicformellons** [arocks/edge#37]
![screenshot from 2015-07-03 14 15 43](https://cloud.githubusercontent.com/assets/10334123/8499007/0f176ac4-218e-11e5-83b6-56318190e56c.png)

Failed to get real commands on module "my_proj": python process died with code 1: Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2218, in _find_and_load_unlocked
AttributeError: 'module' object has no attribute '__path__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pycharm/helpers/pycharm/manage_tasks_provider.py", line 20, in <module>
    django.setup()
  File "/home/MfM/.pyenv/versions/MfMedge/lib/python3.4/site-packages/django/__init__.py", line 17, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/MfM/.pyenv/versions/MfMedge/lib/python3.4/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/home/MfM/.pyenv/versions/MfMedge/lib/python3.4/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/MfM/.pyenv/versions/MfMedge/lib/python3.4/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/MfM/.pyenv/versions/3.4.3/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/MfM/my_proj/src/my_proj/settings/development.py", line 5, in <module>
    from utils.misc import get_git_changeset
ImportError: No module named 'utils.misc'; 'utils' is not a package

**Comment by musicformellons** [comment]
Ah, after renaming to utils1 it works... Problem probably caused by django.utils which give a nameclash.
