### ISSUE TITLE
error while installing django-authtools

### ISSUE THREAD

**Issue by tuxador** [arocks/edge#39]
Hi, i'm facing an issue when trying to install requirements, so after i hit : 
`(py3env)[kaddour@archlinux edge $ pip3 install -r requirements.txt` 
i get this error : 
`Requirement already satisfied (use --upgrade to upgrade): Django>=1.8 in /home/kaddour/django/edge/py3env/lib/python3.4/site-packages (from -r requirements/base.txt (line 1))
Collecting django-environ>=0.3.0 (from -r requirements/base.txt (line 2))
  Using cached django-environ-0.3.0.tar.gz
Collecting django-braces>=1.8.0 (from -r requirements/base.txt (line 3))
  Using cached django_braces-1.8.1-py2.py3-none-any.whl
Collecting django-crispy-forms>=1.4.0 (from -r requirements/base.txt (line 4))
Collecting django-admin-bootstrapped>=2.4.0 (from -r requirements/base.txt (line 5))
Collecting django-authtools>=1.2.0 (from -r requirements/base.txt (line 6))
  Using cached django-authtools-1.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-pdsxcxi3/django-authtools/setup.py", line 23, in <module>
        long_description='\n\n'.join([read('README.rst'), read('CHANGES.rst')]),
      File "/tmp/pip-build-pdsxcxi3/django-authtools/setup.py", line 10, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 721: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-pdsxcxi3/django-authtools `

-----
So i think this line has to do with utf8 encoding "stuff"
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 721: ordinal not in range(128)`

Any help is welcome (i'm an almost perfect **noob**)

**Comment by arocks** [comment]
This looks like an environment issue. Possibly your pip is confused about which virtual environment to pick. Just to add, I am using Arch Linux too and haven't faced any such issues so far. Could you check at your end?

Thanks!
